
import javax.swing.JOptionPane;

public class Bicicletas extends javax.swing.JFrame {

    public Bicicletas() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBicicletas = new javax.swing.JTable();
        BT_ListarBicicletas = new javax.swing.JButton();
        BT_BorrarBicicletas = new javax.swing.JButton();
        BT_AgregarBicicletas = new javax.swing.JButton();
        BT_ActualizarBicicletas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Bicicletas");
        setLocationByPlatform(true);

        TablaBicicletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(TablaBicicletas);

        BT_ListarBicicletas.setText("Actualizar Vista");
        BT_ListarBicicletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarBicicletasMouseClicked(evt);
            }
        });
        BT_ListarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarBicicletasActionPerformed(evt);
            }
        });

        BT_BorrarBicicletas.setText("Borrar Bicicleta");
        BT_BorrarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarBicicletasActionPerformed(evt);
            }
        });

        BT_AgregarBicicletas.setText("Agregar Bicicleta");
        BT_AgregarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarBicicletasActionPerformed(evt);
            }
        });

        BT_ActualizarBicicletas.setText("Editar Bicicleta");
        BT_ActualizarBicicletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ActualizarBicicletasMouseClicked(evt);
            }
        });
        BT_ActualizarBicicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ActualizarBicicletasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Inventario de Bicicletas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_AgregarBicicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_ActualizarBicicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ListarBicicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_BorrarBicicletas)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_AgregarBicicletas)
                    .addComponent(BT_BorrarBicicletas)
                    .addComponent(BT_ActualizarBicicletas)
                    .addComponent(BT_ListarBicicletas))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarBicicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarBicicletasActionPerformed

    private void BT_ListarBicicletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarBicicletasMouseClicked

        Actualiar();


    }//GEN-LAST:event_BT_ListarBicicletasMouseClicked

    private void BT_BorrarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarBicicletasActionPerformed
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaBicicletas.getSelectedRow();
            String id = TablaBicicletas.getValueAt(index, 0).toString();

            if (new Conexion().deleteBicicletas(id)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan datos asociados.");
            }

        }
    }//GEN-LAST:event_BT_BorrarBicicletasActionPerformed

    private void BT_AgregarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarBicicletasActionPerformed
        // TODO add your handling code here:
        (new BicicletasAdd()).setVisible(true);
        Actualiar();
    }//GEN-LAST:event_BT_AgregarBicicletasActionPerformed

    private void BT_ActualizarBicicletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ActualizarBicicletasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ActualizarBicicletasMouseClicked

    private void BT_ActualizarBicicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ActualizarBicicletasActionPerformed
        // TODO add your handling code here:
        int index = TablaBicicletas.getSelectedRow();
        if (index > 0) {

            (new BicicletasAdd(
                    TablaBicicletas.getValueAt(index, 0).toString(),
                    TablaBicicletas.getValueAt(index, 1).toString(),
                    TablaBicicletas.getValueAt(index, 2).toString(),
                    TablaBicicletas.getValueAt(index, 3).toString()
            )).setVisible(true);

        }

        Actualiar();

    }//GEN-LAST:event_BT_ActualizarBicicletasActionPerformed

    private void Actualiar() {

        TablaBicicletas.setModel(new Conexion().getDataBicicletas());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ActualizarBicicletas;
    private javax.swing.JButton BT_AgregarBicicletas;
    private javax.swing.JButton BT_BorrarBicicletas;
    private javax.swing.JButton BT_ListarBicicletas;
    private javax.swing.JTable TablaBicicletas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
