
import javax.swing.JOptionPane;

public class Clientes extends javax.swing.JFrame {

    public Clientes() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        BT_ListarClientes = new javax.swing.JButton();
        BT_BorrarCliente = new javax.swing.JButton();
        BT_Agregar = new javax.swing.JButton();
        BT_Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Clientes");
        setLocationByPlatform(true);

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        BT_ListarClientes.setText("Actualizar");
        BT_ListarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarClientesMouseClicked(evt);
            }
        });
        BT_ListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarClientesActionPerformed(evt);
            }
        });

        BT_BorrarCliente.setText("Eliminar");
        BT_BorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarClienteActionPerformed(evt);
            }
        });

        BT_Agregar.setText("Agregar");
        BT_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarActionPerformed(evt);
            }
        });

        BT_Actualizar.setText("Editar");
        BT_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ActualizarMouseClicked(evt);
            }
        });
        BT_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BT_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ListarClientes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_BorrarCliente)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_ListarClientes)
                    .addComponent(BT_BorrarCliente)
                    .addComponent(BT_Agregar)
                    .addComponent(BT_Actualizar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarClientesActionPerformed

    private void BT_ListarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarClientesMouseClicked

        Actualiar();
    }//GEN-LAST:event_BT_ListarClientesMouseClicked

    private void BT_BorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarClienteActionPerformed
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaClientes.getSelectedRow();
            String fabrica = TablaClientes.getValueAt(index, 0).toString();

            if (new Conexion().deleteClientes(fabrica)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan compras  con este cliente.");
            }

        }
    }//GEN-LAST:event_BT_BorrarClienteActionPerformed

    private void BT_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarActionPerformed
        // TODO add your handling code here:
        (new ClientesAdd()).setVisible(true);
        Actualiar();
    }//GEN-LAST:event_BT_AgregarActionPerformed

    private void BT_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ActualizarMouseClicked

    private void BT_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ActualizarActionPerformed
        // TODO add your handling code here:
        int index = TablaClientes.getSelectedRow();
        if (index > 0) {
            // (String fecha,String contrasena, String celular,String email, String apellido, String nombre, String alias)
            (new ClientesAdd(
                    TablaClientes.getValueAt(index, 5).toString(),
                    "",
                    TablaClientes.getValueAt(index, 4).toString(),
                    TablaClientes.getValueAt(index, 3).toString(),
                    TablaClientes.getValueAt(index, 2).toString(),
                    TablaClientes.getValueAt(index, 1).toString(),
                    TablaClientes.getValueAt(index, 0).toString()
            )).setVisible(true);

        }

        Actualiar();

    }//GEN-LAST:event_BT_ActualizarActionPerformed

    private void Actualiar() {

        TablaClientes.setModel(new Conexion().getDataClientes());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Actualizar;
    private javax.swing.JButton BT_Agregar;
    private javax.swing.JButton BT_BorrarCliente;
    private javax.swing.JButton BT_ListarClientes;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
