
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Compras extends javax.swing.JFrame {

    public Compras() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaClientes = new javax.swing.JTable();
        BT_ListarCompras = new javax.swing.JButton();
        BT_BorrarCompra = new javax.swing.JButton();
        BT_Agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Clientes");
        setLocationByPlatform(true);

        TablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaClientes);

        BT_ListarCompras.setText("Actualizar");
        BT_ListarCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarComprasMouseClicked(evt);
            }
        });
        BT_ListarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarComprasActionPerformed(evt);
            }
        });

        BT_BorrarCompra.setText("Eliminar");
        BT_BorrarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarCompraActionPerformed(evt);
            }
        });

        BT_Agregar.setText("Agregar");
        BT_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Compras");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BT_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_ListarCompras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_BorrarCompra)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_ListarCompras)
                    .addComponent(BT_BorrarCompra)
                    .addComponent(BT_Agregar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarComprasActionPerformed

    private void BT_ListarComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarComprasMouseClicked

        Actualiar();
    }//GEN-LAST:event_BT_ListarComprasMouseClicked

    private void BT_BorrarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarCompraActionPerformed
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaClientes.getSelectedRow();
            String fabrica = TablaClientes.getValueAt(index, 0).toString();

            if (new Conexion().deleteCompras(fabrica)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan compras  con este cliente.");
            }

        }
    }//GEN-LAST:event_BT_BorrarCompraActionPerformed

    private void BT_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarActionPerformed
        // TODO add your handling code here:
        (new ComprasAdd()).setVisible(true);
        Actualiar();
    }//GEN-LAST:event_BT_AgregarActionPerformed

    private void Actualiar() {

        TablaClientes.setModel(new Conexion().getDataCompras());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Agregar;
    private javax.swing.JButton BT_BorrarCompra;
    private javax.swing.JButton BT_ListarCompras;
    private javax.swing.JTable TablaClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
