
import javax.swing.JOptionPane;

public class Fabricas extends javax.swing.JFrame {

    public Fabricas() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFabricas = new javax.swing.JTable();
        BT_ListarFabricas = new javax.swing.JButton();
        BT_BorrarFabrica = new javax.swing.JButton();
        BT_Agregar = new javax.swing.JButton();
        BT_Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLocationByPlatform(true);

        TablaFabricas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaFabricas);

        BT_ListarFabricas.setText("Actualizar");
        BT_ListarFabricas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarFabricasMouseClicked(evt);
            }
        });
        BT_ListarFabricas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarFabricasActionPerformed(evt);
            }
        });

        BT_BorrarFabrica.setText("Eliminar");
        BT_BorrarFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarFabricaActionPerformed(evt);
            }
        });

        BT_Agregar.setText("Agregar Fabricante");
        BT_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarActionPerformed(evt);
            }
        });

        BT_Actualizar.setText("Editar");
        BT_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ActualizarMouseClicked(evt);
            }
        });
        BT_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listado de Fabricantes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ListarFabricas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_BorrarFabrica)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Agregar)
                    .addComponent(BT_Actualizar)
                    .addComponent(BT_BorrarFabrica)
                    .addComponent(BT_ListarFabricas))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarFabricasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarFabricasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarFabricasActionPerformed

    private void BT_ListarFabricasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarFabricasMouseClicked

        Actualiar();
    }//GEN-LAST:event_BT_ListarFabricasMouseClicked

    private void BT_BorrarFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarFabricaActionPerformed
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaFabricas.getSelectedRow();
            String fabrica = TablaFabricas.getValueAt(index, 0).toString();

            if (new Conexion().deleteFabricas(fabrica)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan bicicletas con este fabricante.");
            }

        }
    }//GEN-LAST:event_BT_BorrarFabricaActionPerformed

    private void BT_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarActionPerformed
        // TODO add your handling code here:
        String name = JOptionPane.showInputDialog("Escriba el nombre de la fabrica");
        if (name.length() > 0) {
            if ((new Conexion()).addFabrica(name)) {
                JOptionPane.showMessageDialog(null, "Regstro agregado");
            } else {
                JOptionPane.showMessageDialog(null, "no se puede agregar el registro");
            }

        }
        Actualiar();
    }//GEN-LAST:event_BT_AgregarActionPerformed

    private void BT_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ActualizarMouseClicked

    private void BT_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ActualizarActionPerformed
        // TODO add your handling code here:
        int index = TablaFabricas.getSelectedRow();
        if (index > 0) {
            String fabrica = TablaFabricas.getValueAt(index, 0).toString();

            String name = JOptionPane.showInputDialog("Escriba el nombre nuevo de la fabrica " + fabrica);
            if (name.length() > 0) {

                if ((new Conexion()).updateFabricas(fabrica, name)) {
                    JOptionPane.showMessageDialog(null, "Regstro actualizado");
                } else {
                    JOptionPane.showMessageDialog(null, "no se puede actualizado el registro");
                }

            }

        }

        Actualiar();

    }//GEN-LAST:event_BT_ActualizarActionPerformed

    private void Actualiar() {

        TablaFabricas.setModel(new Conexion().getDataFabricas());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Actualizar;
    private javax.swing.JButton BT_Agregar;
    private javax.swing.JButton BT_BorrarFabrica;
    private javax.swing.JButton BT_ListarFabricas;
    private javax.swing.JTable TablaFabricas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
