
import javax.swing.JOptionPane;

public class Motocicletas extends javax.swing.JFrame {

    public Motocicletas() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMotocicletas = new javax.swing.JTable();
        BT_ListarMotocicletas = new javax.swing.JButton();
        BT_BorrarMotocicleta = new javax.swing.JButton();
        BT_AgregarMotocicletas = new javax.swing.JButton();
        BT_ActualizarMotocicleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Motocicletas Electricas");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        TablaMotocicletas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(TablaMotocicletas);

        BT_ListarMotocicletas.setText("Actualizar");
        BT_ListarMotocicletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarMotocicletasMouseClicked(evt);
            }
        });
        BT_ListarMotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarMotocicletasActionPerformed(evt);
            }
        });

        BT_BorrarMotocicleta.setText("Eliminar");
        BT_BorrarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarMotocicletaActionPerformed(evt);
            }
        });

        BT_AgregarMotocicletas.setText("Agregar Motocicleta");
        BT_AgregarMotocicletas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarMotocicletasActionPerformed(evt);
            }
        });

        BT_ActualizarMotocicleta.setText("Editar Motocicleta");
        BT_ActualizarMotocicleta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ActualizarMotocicletaMouseClicked(evt);
            }
        });
        BT_ActualizarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ActualizarMotocicletaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Inventario de Motocicletas Electricas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_AgregarMotocicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_ActualizarMotocicleta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ListarMotocicletas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_BorrarMotocicleta)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_ListarMotocicletas)
                    .addComponent(BT_AgregarMotocicletas)
                    .addComponent(BT_ActualizarMotocicleta)
                    .addComponent(BT_BorrarMotocicleta))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarMotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarMotocicletasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarMotocicletasActionPerformed

    private void BT_ListarMotocicletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarMotocicletasMouseClicked

        Actualiar();


    }//GEN-LAST:event_BT_ListarMotocicletasMouseClicked

    private void BT_BorrarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarMotocicletaActionPerformed
        String[] options = {"Si", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaMotocicletas.getSelectedRow();
            String id = TablaMotocicletas.getValueAt(index, 0).toString();

            if (new Conexion().deleteMotocicletas(id)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan datos asociados.");
            }

        }
    }//GEN-LAST:event_BT_BorrarMotocicletaActionPerformed

    private void BT_AgregarMotocicletasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarMotocicletasActionPerformed
        // TODO add your handling code here:
        (new MotocicletasAdd()).setVisible(true);
        Actualiar();
    }//GEN-LAST:event_BT_AgregarMotocicletasActionPerformed

    private void BT_ActualizarMotocicletaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ActualizarMotocicletaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ActualizarMotocicletaMouseClicked

    private void BT_ActualizarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ActualizarMotocicletaActionPerformed
        // TODO add your handling code here:
        int index = TablaMotocicletas.getSelectedRow();
        if (index > 0) {

            (new MotocicletasAdd(
                    TablaMotocicletas.getValueAt(index, 0).toString(),
                    TablaMotocicletas.getValueAt(index, 1).toString(),
                    TablaMotocicletas.getValueAt(index, 2).toString(),
                    TablaMotocicletas.getValueAt(index, 3).toString(),
                    TablaMotocicletas.getValueAt(index, 4).toString(),
                    TablaMotocicletas.getValueAt(index, 5).toString()
            )).setVisible(true);

        }

        Actualiar();

    }//GEN-LAST:event_BT_ActualizarMotocicletaActionPerformed

    private void Actualiar() {

        TablaMotocicletas.setModel(new Conexion().getDataMotocicletas());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_ActualizarMotocicleta;
    private javax.swing.JButton BT_AgregarMotocicletas;
    private javax.swing.JButton BT_BorrarMotocicleta;
    private javax.swing.JButton BT_ListarMotocicletas;
    private javax.swing.JTable TablaMotocicletas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
