
import javax.swing.JOptionPane;

public class Proveedor extends javax.swing.JFrame {

    public Proveedor() {

        initComponents();
        Actualiar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaProveedores = new javax.swing.JTable();
        BT_ListarProveedores = new javax.swing.JButton();
        BT_BorrarProveedor = new javax.swing.JButton();
        BT_Agregar = new javax.swing.JButton();
        BT_Actualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Proveedores");
        setLocationByPlatform(true);

        TablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaProveedores);

        BT_ListarProveedores.setText("Actualizar");
        BT_ListarProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ListarProveedoresMouseClicked(evt);
            }
        });
        BT_ListarProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ListarProveedoresActionPerformed(evt);
            }
        });

        BT_BorrarProveedor.setText("Eliminar Proveedor");
        BT_BorrarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_BorrarProveedorActionPerformed(evt);
            }
        });

        BT_Agregar.setText("Agregar Proveedor");
        BT_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_AgregarActionPerformed(evt);
            }
        });

        BT_Actualizar.setText("Editar Proveedor");
        BT_Actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BT_ActualizarMouseClicked(evt);
            }
        });
        BT_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_ActualizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Proveedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_Actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BT_ListarProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BT_BorrarProveedor)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BT_Agregar)
                    .addComponent(BT_Actualizar)
                    .addComponent(BT_ListarProveedores)
                    .addComponent(BT_BorrarProveedor))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_ListarProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ListarProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ListarProveedoresActionPerformed

    private void BT_ListarProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ListarProveedoresMouseClicked

        Actualiar();
    }//GEN-LAST:event_BT_ListarProveedoresMouseClicked

    private void BT_BorrarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_BorrarProveedorActionPerformed
        String[] options = {"Yes", "No"};
        int answ = JOptionPane.showOptionDialog(null, "Esta seguro?", "Confirmar borrado", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1]);

        if (answ == 0) {
            int index = TablaProveedores.getSelectedRow();
            String prov_id = TablaProveedores.getValueAt(index, 0).toString();

            if (new Conexion().deleteProveedor(prov_id)) {
                JOptionPane.showMessageDialog(null, "Regstro eliminado");

                Actualiar();
            } else {
                JOptionPane.showMessageDialog(null, "Registro no eliminado, puede que existan datos asociados.");
            }

        }
    }//GEN-LAST:event_BT_BorrarProveedorActionPerformed

    private void BT_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_AgregarActionPerformed
        // TODO add your handling code here:
        (new ProveedorAdd()).setVisible(true);
        Actualiar();
    }//GEN-LAST:event_BT_AgregarActionPerformed

    private void BT_ActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BT_ActualizarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BT_ActualizarMouseClicked

    private void BT_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_ActualizarActionPerformed
        // TODO add your handling code here:
        int index = TablaProveedores.getSelectedRow();
        if (index > 0) {
            // 
            (new ProveedorAdd(
                    TablaProveedores.getValueAt(index, 0).toString(),
                    TablaProveedores.getValueAt(index, 1).toString(),
                    TablaProveedores.getValueAt(index, 2).toString(),
                    TablaProveedores.getValueAt(index, 3).toString()
            )).setVisible(true);

        }

        Actualiar();

    }//GEN-LAST:event_BT_ActualizarActionPerformed

    private void Actualiar() {

        TablaProveedores.setModel(new Conexion().getDataProveedor());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Actualizar;
    private javax.swing.JButton BT_Agregar;
    private javax.swing.JButton BT_BorrarProveedor;
    private javax.swing.JButton BT_ListarProveedores;
    private javax.swing.JTable TablaProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
